"""Migrated legacy TeacherTextbook builder."""

from __future__ import annotations

from typing import Any

from radjax_tome._lazy_exports import (
    LazyExportMap,
    lazy_export_names,
    resolve_lazy_export,
)
from radjax_tome.builder.backend_textbook import (
    BackendTeacherTextbookBuildConfig,
    build_backend_teacher_textbook,
    build_streaming_backend_teacher_textbook,
    teacher_backend_config_from_build_config,
)
from radjax_tome.builder.c6_integration import (
    C6_COVERAGE_REPORT_SCHEMA,
    C6_SELECTION_INTEGRATION_POLICY,
    C6_VALIDATION_SCHEMA,
    GLOBAL_ONLY_SELECTION_POLICY,
    build_corridor_coverage_report,
    export_production_global_board_supply,
    validate_integrated_selection_contract,
    write_corridor_coverage_report,
)
from radjax_tome.builder.config import (
    CANONICAL_BUILD_INTENT_SCHEMA,
    EXECUTION_PLAN_SCHEMA,
    NORMALIZED_PRODUCTION_REQUEST_SCHEMA,
    PRODUCTION_PRESETS,
    RESOLVED_BUILD_CONFIG_SCHEMA,
    CompatibilityOverrides,
    CorpusIntent,
    CorridorPolicyIntent,
    ExecutionIntent,
    NormalizedProductionBuildRequest,
    OutputIntent,
    PackageIntent,
    ResolutionMetadata,
    ResolvedTomeBuildConfig,
    SelectionIntent,
    TeacherIntent,
    TokenBehaviorIntent,
    TomeBuildIntent,
    TomeExecutionPlan,
    adapt_legacy_production_build_config,
    apply_production_advanced_overrides,
    apply_production_preset,
    canonical_production_build_intent,
    derive_execution_plan,
    normalize_cli_production_build_request,
    normalize_production_build_request,
    production_build_config_from_resolved,
    resolve_tome_build_intent,
    resolved_tome_build_config_payload,
    selection_authority_hash_v1,
    selection_authority_payload_v1,
    validate_resolved_tome_build_config,
    validate_tome_build_intent,
)
from radjax_tome.builder.exemplar_delivery import (
    EXEMPLAR_DELIVERY_PARITY_REPORT_SCHEMA,
    EXEMPLAR_DELIVERY_REPORT_FILENAME,
    EXEMPLAR_DELIVERY_REPORT_SCHEMA,
    ExemplarDeliveryConfig,
    compare_exemplar_delivery_artifacts,
    materialize_selected_exemplar_delivery,
    validate_selected_exemplar_delivery,
)
from radjax_tome.builder.exemplar_selection import (
    EXEMPLAR_SELECTION_MANIFEST_FILENAME,
    EXEMPLAR_SELECTION_MANIFEST_SCHEMA,
    MULTI_LEADERBOARD_SELECTOR_POLICY,
    ExemplarCandidate,
    build_exemplar_selection_manifest,
    extract_one_pass_candidates,
    extract_score_pass_candidates,
    select_exemplars,
    validate_exemplar_selection_manifest,
    write_exemplar_selection_manifest,
)
from radjax_tome.builder.production import (
    PRODUCTION_BUILD_REPORT_FILENAME,
    PRODUCTION_BUILD_REPORT_SCHEMA,
    ProductionBuildConfig,
    build_production_gpu_tome,
    render_production_build_summary,
    write_production_build_report,
)
from radjax_tome.builder.teacher_textbook import (
    TEACHER_TEXTBOOK_VERSION,
    TeacherTextbookBuildConfig,
    TeacherTextbookValidationReport,
    TinyTextExample,
    build_fake_teacher_textbook,
    build_hf_teacher_textbook,
    build_teacher_textbook,
    load_text_examples,
    validate_teacher_textbook,
    write_teacher_textbook_validation_report,
)

_LAZY_EXPORTS: LazyExportMap = {
    "MULTI_GPU_PATH_B_REPORT_FILENAME": (
        "radjax_tome.builder.multi_gpu_path_b",
        "MULTI_GPU_PATH_B_REPORT_FILENAME",
    ),
    "MULTI_GPU_PATH_B_REPORT_SCHEMA": (
        "radjax_tome.builder.multi_gpu_path_b",
        "MULTI_GPU_PATH_B_REPORT_SCHEMA",
    ),
    "MULTI_GPU_WORKER_MANIFEST_FILENAME": (
        "radjax_tome.builder.multi_gpu_path_b",
        "MULTI_GPU_WORKER_MANIFEST_FILENAME",
    ),
    "MULTI_GPU_WORKER_MANIFEST_SCHEMA": (
        "radjax_tome.builder.multi_gpu_path_b",
        "MULTI_GPU_WORKER_MANIFEST_SCHEMA",
    ),
    "MultiGPUPathBConfig": (
        "radjax_tome.builder.multi_gpu_path_b",
        "MultiGPUPathBConfig",
    ),
    "build_path_b_assignments": (
        "radjax_tome.builder.multi_gpu_path_b",
        "build_path_b_assignments",
    ),
    "merge_path_b_candidate_records": (
        "radjax_tome.builder.multi_gpu_path_b",
        "merge_path_b_candidate_records",
    ),
    "normalize_multi_gpu_devices": (
        "radjax_tome.builder.multi_gpu_path_b",
        "normalize_multi_gpu_devices",
    ),
    "render_multi_gpu_path_b_summary": (
        "radjax_tome.builder.multi_gpu_path_b",
        "render_multi_gpu_path_b_summary",
    ),
    "run_multi_gpu_path_b_candidate_harness": (
        "radjax_tome.builder.multi_gpu_path_b",
        "run_multi_gpu_path_b_candidate_harness",
    ),
}

__all__ = [
    "CANONICAL_BUILD_INTENT_SCHEMA",
    "TEACHER_TEXTBOOK_VERSION",
    "EXECUTION_PLAN_SCHEMA",
    "NORMALIZED_PRODUCTION_REQUEST_SCHEMA",
    "PRODUCTION_PRESETS",
    "RESOLVED_BUILD_CONFIG_SCHEMA",
    "BackendTeacherTextbookBuildConfig",
    "C6_COVERAGE_REPORT_SCHEMA",
    "C6_SELECTION_INTEGRATION_POLICY",
    "C6_VALIDATION_SCHEMA",
    "EXEMPLAR_DELIVERY_PARITY_REPORT_SCHEMA",
    "EXEMPLAR_DELIVERY_REPORT_FILENAME",
    "EXEMPLAR_DELIVERY_REPORT_SCHEMA",
    "EXEMPLAR_SELECTION_MANIFEST_FILENAME",
    "EXEMPLAR_SELECTION_MANIFEST_SCHEMA",
    "MULTI_LEADERBOARD_SELECTOR_POLICY",
    "MULTI_GPU_PATH_B_REPORT_FILENAME",
    "MULTI_GPU_PATH_B_REPORT_SCHEMA",
    "MULTI_GPU_WORKER_MANIFEST_FILENAME",
    "MULTI_GPU_WORKER_MANIFEST_SCHEMA",
    "PRODUCTION_BUILD_REPORT_FILENAME",
    "PRODUCTION_BUILD_REPORT_SCHEMA",
    "ExemplarCandidate",
    "ExemplarDeliveryConfig",
    "CompatibilityOverrides",
    "CorridorPolicyIntent",
    "CorpusIntent",
    "ExecutionIntent",
    "NormalizedProductionBuildRequest",
    "MultiGPUPathBConfig",
    "OutputIntent",
    "PackageIntent",
    "ProductionBuildConfig",
    "ResolvedTomeBuildConfig",
    "ResolutionMetadata",
    "SelectionIntent",
    "GLOBAL_ONLY_SELECTION_POLICY",
    "TeacherIntent",
    "TeacherTextbookBuildConfig",
    "TeacherTextbookValidationReport",
    "TinyTextExample",
    "TokenBehaviorIntent",
    "TomeBuildIntent",
    "TomeExecutionPlan",
    "adapt_legacy_production_build_config",
    "apply_production_advanced_overrides",
    "apply_production_preset",
    "build_backend_teacher_textbook",
    "build_corridor_coverage_report",
    "build_exemplar_selection_manifest",
    "build_fake_teacher_textbook",
    "build_hf_teacher_textbook",
    "build_path_b_assignments",
    "build_production_gpu_tome",
    "build_streaming_backend_teacher_textbook",
    "build_teacher_textbook",
    "canonical_production_build_intent",
    "compare_exemplar_delivery_artifacts",
    "derive_execution_plan",
    "extract_one_pass_candidates",
    "extract_score_pass_candidates",
    "export_production_global_board_supply",
    "load_text_examples",
    "materialize_selected_exemplar_delivery",
    "merge_path_b_candidate_records",
    "normalize_multi_gpu_devices",
    "normalize_cli_production_build_request",
    "normalize_production_build_request",
    "production_build_config_from_resolved",
    "render_multi_gpu_path_b_summary",
    "render_production_build_summary",
    "resolved_tome_build_config_payload",
    "resolve_tome_build_intent",
    "run_multi_gpu_path_b_candidate_harness",
    "select_exemplars",
    "selection_authority_hash_v1",
    "selection_authority_payload_v1",
    "teacher_backend_config_from_build_config",
    "validate_teacher_textbook",
    "validate_tome_build_intent",
    "validate_resolved_tome_build_config",
    "validate_exemplar_selection_manifest",
    "validate_integrated_selection_contract",
    "write_corridor_coverage_report",
    "validate_selected_exemplar_delivery",
    "write_exemplar_selection_manifest",
    "write_production_build_report",
    "write_teacher_textbook_validation_report",
]


def __getattr__(name: str) -> Any:
    return resolve_lazy_export(globals(), _LAZY_EXPORTS, name)


def __dir__() -> list[str]:
    return lazy_export_names(globals(), _LAZY_EXPORTS)
