"""Migrated legacy TeacherTextbook builder."""

from radjax_tome.builder.backend_textbook import (
    BackendTeacherTextbookBuildConfig,
    build_backend_teacher_textbook,
    build_streaming_backend_teacher_textbook,
    teacher_backend_config_from_build_config,
)
from radjax_tome.builder.exemplar_selection import (
    EXEMPLAR_SELECTION_MANIFEST_FILENAME,
    EXEMPLAR_SELECTION_MANIFEST_SCHEMA,
    MULTI_LEADERBOARD_SELECTOR_POLICY,
    ExemplarCandidate,
    build_exemplar_selection_manifest,
    extract_one_pass_candidates,
    extract_score_pass_candidates,
    select_exemplars,
    validate_exemplar_selection_manifest,
    write_exemplar_selection_manifest,
)
from radjax_tome.builder.production import (
    PRODUCTION_BUILD_REPORT_FILENAME,
    PRODUCTION_BUILD_REPORT_SCHEMA,
    ProductionBuildConfig,
    build_production_gpu_tome,
    render_production_build_summary,
    write_production_build_report,
)
from radjax_tome.builder.teacher_textbook import (
    TEACHER_TEXTBOOK_VERSION,
    TeacherTextbookBuildConfig,
    TeacherTextbookValidationReport,
    TinyTextExample,
    build_fake_teacher_textbook,
    build_hf_teacher_textbook,
    build_teacher_textbook,
    load_text_examples,
    validate_teacher_textbook,
    write_teacher_textbook_validation_report,
)

__all__ = [
    "TEACHER_TEXTBOOK_VERSION",
    "BackendTeacherTextbookBuildConfig",
    "EXEMPLAR_SELECTION_MANIFEST_FILENAME",
    "EXEMPLAR_SELECTION_MANIFEST_SCHEMA",
    "MULTI_LEADERBOARD_SELECTOR_POLICY",
    "PRODUCTION_BUILD_REPORT_FILENAME",
    "PRODUCTION_BUILD_REPORT_SCHEMA",
    "ExemplarCandidate",
    "ProductionBuildConfig",
    "TeacherTextbookBuildConfig",
    "TeacherTextbookValidationReport",
    "TinyTextExample",
    "build_backend_teacher_textbook",
    "build_exemplar_selection_manifest",
    "build_fake_teacher_textbook",
    "build_hf_teacher_textbook",
    "build_production_gpu_tome",
    "build_streaming_backend_teacher_textbook",
    "build_teacher_textbook",
    "extract_one_pass_candidates",
    "extract_score_pass_candidates",
    "load_text_examples",
    "render_production_build_summary",
    "select_exemplars",
    "teacher_backend_config_from_build_config",
    "validate_teacher_textbook",
    "validate_exemplar_selection_manifest",
    "write_exemplar_selection_manifest",
    "write_production_build_report",
    "write_teacher_textbook_validation_report",
]
