"""Teacher backend interfaces and fake/synthetic implementations."""

from radjax_tome.backends.base import (
    MIN_CORRIDOR_STAT_TOP_K,
    BackendCapability,
    CpuOrchestrationMode,
    FallbackPolicy,
    RuntimeMode,
    SupportStatus,
    TargetPolicy,
    TeacherBackend,
    TeacherBackendConfig,
    TeacherBatchInput,
    TeacherEmissionBackend,
    TeacherEmissionResult,
    TeacherTargetEmitter,
    gpu_batch_size_candidates,
    resolve_gpu_batch_size_policy,
    validate_gpu_batch_size_policy_config,
)
from radjax_tome.backends.cpu import CPUReferenceTeacherEmissionBackend
from radjax_tome.backends.emission import emit_teacher_target_store
from radjax_tome.backends.fake import (
    FakeNumpyTeacherEmissionBackend,
    FakeTeacherBackend,
)
from radjax_tome.backends.gpu_torch import (
    GPUTorchTeacherEmissionBackend,
    TorchAcceleratorDetection,
    check_gpu_torch_backend_available,
    detect_torch_accelerator,
    diagnose_gpu_torch_backend,
)
from radjax_tome.backends.hf_export import (
    HFTeacherExportConfig,
    HFTeacherExportMetadata,
    build_hf_export_metadata,
    read_hf_export_metadata,
    validate_hf_export_config,
    write_hf_export_metadata,
)
from radjax_tome.backends.hf_specimen import (
    DEFAULT_HF_SPECIMEN_MODEL_ID,
    HFTeacherSpecimenConfig,
    HFTeacherSpecimenSmokeResult,
    HFTeacherSpecimenSwapReport,
    build_hf_teacher_specimen_dry_run,
    build_hf_teacher_specimen_swap_report,
    read_hf_teacher_specimen_report,
    run_hf_teacher_specimen_smoke,
    validate_hf_teacher_specimen_config,
    write_hf_teacher_specimen_report,
)
from radjax_tome.backends.hf_torch import HFTorchTeacherEmissionBackend
from radjax_tome.backends.orchestration import (
    BackendBatchEnvelope,
    BackendRunConfig,
    BackendRunResult,
    run_backend_batches,
)
from radjax_tome.backends.qwen_policy import (
    QwenPolicyEntry,
    QwenPolicyMap,
    QwenResolution,
    load_qwen_policy,
    resolve_qwen_policy,
    resolve_qwen_policy_map,
)
from radjax_tome.backends.registry import (
    create_backend,
    list_backend_capabilities,
    register_backend,
)
from radjax_tome.backends.synthetic import SyntheticTeacherBackend

__all__ = [
    "BackendCapability",
    "BackendBatchEnvelope",
    "BackendRunConfig",
    "BackendRunResult",
    "CPUReferenceTeacherEmissionBackend",
    "CpuOrchestrationMode",
    "FallbackPolicy",
    "MIN_CORRIDOR_STAT_TOP_K",
    "FakeNumpyTeacherEmissionBackend",
    "FakeTeacherBackend",
    "DEFAULT_HF_SPECIMEN_MODEL_ID",
    "GPUTorchTeacherEmissionBackend",
    "HFTeacherExportConfig",
    "HFTeacherExportMetadata",
    "HFTeacherSpecimenConfig",
    "HFTeacherSpecimenSmokeResult",
    "HFTeacherSpecimenSwapReport",
    "HFTorchTeacherEmissionBackend",
    "QwenPolicyEntry",
    "QwenPolicyMap",
    "QwenResolution",
    "RuntimeMode",
    "SupportStatus",
    "SyntheticTeacherBackend",
    "TargetPolicy",
    "TeacherBackend",
    "TeacherBackendConfig",
    "TeacherBatchInput",
    "TeacherEmissionBackend",
    "TeacherEmissionResult",
    "TeacherTargetEmitter",
    "TorchAcceleratorDetection",
    "build_hf_export_metadata",
    "build_hf_teacher_specimen_dry_run",
    "build_hf_teacher_specimen_swap_report",
    "check_gpu_torch_backend_available",
    "create_backend",
    "diagnose_gpu_torch_backend",
    "detect_torch_accelerator",
    "emit_teacher_target_store",
    "gpu_batch_size_candidates",
    "list_backend_capabilities",
    "load_qwen_policy",
    "read_hf_export_metadata",
    "read_hf_teacher_specimen_report",
    "resolve_gpu_batch_size_policy",
    "resolve_qwen_policy",
    "resolve_qwen_policy_map",
    "run_hf_teacher_specimen_smoke",
    "run_backend_batches",
    "register_backend",
    "validate_hf_export_config",
    "validate_gpu_batch_size_policy_config",
    "validate_hf_teacher_specimen_config",
    "write_hf_export_metadata",
    "write_hf_teacher_specimen_report",
]
